### PR TITLE
added support for mutations

### PR DESCRIPTION
**Pull request by emanuelet**

### CODE REVIEW

**Comment by rbonillajr** [comment]
Could you review the unit tests?

**Comment by rbonillajr** [comment]
Please check tests coverage

**Comment by emanuelet** [comment]
> Please check tests coverage

should be ok now

**Comment by rbonillajr** [comment]
Hello @emanuelet, I am waiting for the fix of the comments to generate a new release

**Comment by emanuelet** [comment]
I believe that the unit tests have passed. What comments are you referring to ?

**Comment by rbonillajr** [comment]
> I believe that the unit tests have passed. What comments are you referring to ?

I left you comments in the code, you can review it in the pull request

**Comment by emanuelet** [comment]
> > I believe that the unit tests have passed. What comments are you referring to ?
> 
> I left you comments in the code, you can review it in the pull request

I think they got removed when I pushed the last commit, because I cannot see any comments

**Comment by rbonillajr** [comment]
> authorization: `Bearer ${context.token}`

my comments were:
- In the authorization include it as a parameter since it is possible that another type of authorization is used
```
headers: { authorization: `Bearer ${context.token}` }
```
- add other task to lint fix for example: 
lint:fix

**Comment by emanuelet** [comment]
would this do?

**Comment by rbonillajr** [comment]
I recommended include text Bearer into property context.auth_token

**Comment by emanuelet** [comment]
ooops. Apologies I should have run the tests before pushing. Now they are passing for me.
I rename the property to `auth_token` to make it more generic and should support any type of auth you throw at it

**Review by rbonillajr — APPROVED** [review]

**Comment by rbonillajr** [comment]
Thank for collaborate

**Comment by rbonillajr** [comment]
@emanuelet, package is ready on npm

**Pull request merged**
